Repository MagnoCarta/Elysium, pull requests merged in 2020-06, with the labels that each got.

#1 Arquitetura app kit
  .DS_Store
  Elysis.xcodeproj/project.pbxproj
  Elysis.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Elysis.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Elysis/Controller/AppDelegate.swift
  Elysis/Controller/ViewController.swift
  Elysis/Elysis.entitlements
  Elysis/Info.plist
  Elysis/Model/BotoesMenu/Continuar.swift
  Elysis/Model/BotoesMenu/NovoJogo.swift
  Elysis/Model/BotoesMenu/Opcoes.swift
  Elysis/Model/Confirmar.swift
  Elysis/Model/GameData.swift
  Elysis/Model/SoundTrack.swift
  Elysis/Model/Sprites.swift
  Elysis/View/Assets.xcassets/AppIcon.appiconset/Contents.json
  Elysis/View/Assets.xcassets/Contents.json
  Elysis/View/Base.lproj/Main.storyboard
  ElysisTests/ElysisTests.swift
  ElysisTests/Info.plist
  ElysisUITests/ElysisUITests.swift
  ElysisUITests/Info.plist
  GameChallenge.xcodeproj/project.pbxproj
  GameChallenge/.DS_Store
  GameChallenge/Controller/GameScene.swift
  GameChallenge/Controller/ViewController.swift
  GameChallenge/View/.DS_Store
  GameChallenge/View/Actions.sks
  GameChallenge/View/GameScene.sks
Labels: enhancement, good first issue

#2 Correcoes
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/ViewController.swift
  Elysis/Info.plist
  Elysis/Model/BotoesMenu/Continuar.swift
  Elysis/Model/BotoesMenu/NovoJogo.swift
  Elysis/Model/BotoesMenu/Opcoes.swift
  Elysis/Model/Confirmar.swift
  Elysis/Model/Sprites.swift
  Elysis/View/Base.lproj/Cover.storyboard
  Elysis/View/Page.storyboard
  Elysis/View/Settings.storyboard
Labels: question

#3 Api
  .DS_Store
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/ApiController.swift
  Elysis/Controller/ViewController.swift
  Elysis/Elysis.entitlements
  Elysis/Model/ApiModel.swift
  Elysis/Model/Sprites.swift
  Elysis/View/Assets.xcassets/Livrinho.imageset/Contents.json
  Elysis/View/Assets.xcassets/Livrinho.imageset/Livrinho.png
Labels: enhancement

#4 Data persistence
  Elysis.xcodeproj/project.pbxproj
  Elysis/.DS_Store
  Elysis/Controller/ViewController.swift
  Elysis/Model/.DS_Store
  Elysis/Model/GameState.swift
  Elysis/Model/Interaction.swift
  Elysis/View/Base.lproj/Cover.storyboard
Labels: enhancement

#5 refactoring of GameState class
  Elysis/Model/GameState.swift
Labels: documentation, enhancement

#8 Data persistence
  Elysis/Controller/ApiController.swift
  Elysis/Controller/ViewController.swift
  Elysis/Model/GameState.swift
Labels: enhancement

#9 Options
  Elysis.xcodeproj/project.pbxproj
  Elysis/.DS_Store
  Elysis/Controller/AppDelegate.swift
  Elysis/Controller/SettingsViewController.swift
  Elysis/Controller/ViewController.swift
  Elysis/View/Base.lproj/Cover.storyboard
  Elysis/View/Settings.storyboard
Labels: enhancement

#10 adding safe force unwrapping for practical purposes
  Elysis/Model/GameState.swift
Labels: enhancement

#12 Barra de texto, Lapis, e um monte de coisa
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/ConstraintsPageViewController .swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/SettingsViewController.swift
  Elysis/Controller/ViewController.swift
  Elysis/Controller/teste.swift
  Elysis/Model/TelaDaPagina/BarraDeTexto.swift
  Elysis/Model/TelaDaPagina/LapisFeedback.swift
  Elysis/Model/TelaDaPagina/OptionButton.swift
  Elysis/Model/TelaDaPagina/Pagina.swift
  Elysis/Model/TelaDaPagina/TextoNormal.swift
  Elysis/View/Assets.xcassets/BarraDeTextoBackground.imageset/BarraDeTextoBackground.png
  Elysis/View/Assets.xcassets/BarraDeTextoBackground.imageset/Contents.json
Labels: bug, enhancement

#13 Animar
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/teste.swift
  Elysis/Model/TelaDaPagina/Pagina.swift
  Elysis/Model/TelaDaPagina/TextoNormal.swift
  Elysis/View/Assets.xcassets/LivroPrincipal1.imageset/Contents.json
  Elysis/View/Assets.xcassets/LivroPrincipal1.imageset/LivroPrincipal1.png
  Elysis/View/Assets.xcassets/PaginaAberta.imageset/PaginaAberta.png
  Elysis/View/Assets.xcassets/PaginaP.imageset/Contents.json
  Elysis/View/Assets.xcassets/PaginaP.imageset/PaginaP.png
Labels: bug, enhancement

#14 Preparacao
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/ConstraintsPageViewController .swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/SettingsViewController.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
  Elysis/Controller/ViewController.swift
  Elysis/View/Assets.xcassets/10.imageset/10.jpg
  Elysis/View/Assets.xcassets/BackgroundGame.imageset/BackgroundGame.png
  Elysis/View/Assets.xcassets/BackgroundGame.imageset/Contents.json
  Elysis/View/Assets.xcassets/CapaSemSimbolo.imageset/Componente 6 – 1.png
  Elysis/View/Assets.xcassets/CapaSemSimbolo.imageset/Contents.json
  Elysis/View/Assets.xcassets/Livrinho.imageset/Contents.json
  Elysis/View/Assets.xcassets/Livrinho.imageset/Livrinho.png
  Elysis/View/Assets.xcassets/LivrinhoCorreto.imageset/LivrinhoCorreto.png
  Elysis/View/Assets.xcassets/LivroAbertoPrincipalAzulRoxeado.imageset/Contents.json
  Elysis/View/Assets.xcassets/LivroAbertoPrincipalAzulRoxeado.imageset/LivroAbertoPrincipalAzulRoxeado.png
  Elysis/View/Assets.xcassets/LivroPrincipal1.imageset/Contents.json
  Elysis/View/Assets.xcassets/LivroPrincipal1.imageset/LivroPrincipal1.png
  Elysis/View/Assets.xcassets/MinhaIdeiaCapa.imageset/Contents.json
  Elysis/View/Assets.xcassets/MinhaIdeiaCapa.imageset/MinhaIdeiaCapa.png
  Elysis/View/Assets.xcassets/PaginaLegal.imageset/Contents.json
  Elysis/View/Assets.xcassets/PaginaLegal.imageset/PaginaLegal.png
  Elysis/View/Assets.xcassets/PaginaNormal.imageset/PaginaNormal.png
  Elysis/View/Assets.xcassets/PaginaP.imageset/PaginaP.png
  Elysis/View/Assets.xcassets/TelaDePagina.imageset/TelaDePagina.png
  Elysis/View/Assets.xcassets/capaDoLivroOficialProntoPronto.imageset/Contents.json
  Elysis/View/Assets.xcassets/capaDoLivroOficialProntoPronto.imageset/capaDoLivroOficialProntoPronto.png
Labels: bug

#15 Pagina animada
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/ConstraintsPageViewController .swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/TelaDaPagina/PontaDaPaginaAnimada.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
  Elysis/Controller/ViewController.swift
  Elysis/Model/GameData.swift
  Elysis/Model/Sprites.swift
  Elysis/View/Assets.xcassets/Cover.imageset/Contents.json
  Elysis/View/Assets.xcassets/Cover.imageset/Cover.png
  Elysis/View/Assets.xcassets/LettersCover.imageset/Contents.json
  Elysis/View/Assets.xcassets/LettersCover.imageset/LettersCover.png
  Elysis/View/Assets.xcassets/PontaDireita.imageset/PontaDireita.png
  Elysis/View/Assets.xcassets/PontaEsquerda.imageset/PontaEsquerda.png
  Elysis/View/Assets.xcassets/PontinhaDireita.imageset/Contents.json
  Elysis/View/Assets.xcassets/PontinhaDireita.imageset/PontinhaDireita.png
  Elysis/View/Assets.xcassets/PontinhaEsquerda.imageset/Contents.json
  Elysis/View/Assets.xcassets/PontinhaEsquerda.imageset/PontinhaEsquerda.png
Labels: bug, enhancement, good first issue

#16 Load
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/HistoryModel.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
Labels: bug, enhancement

#17 Fazendo oque nao devia
  Elysis/Controller/ConstraintsPageViewController .swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/LapisFeedback.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
Labels: bug, enhancement, good first issue, help wanted, question

#21 Arrumando capa e afins
  Elysis.xcodeproj/xcshareddata/xcschemes/Elysis.xcscheme
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/ViewController.swift
Labels: bug

#20 Testes unitarios
  Elysis.xcodeproj/project.pbxproj
  Elysis.xcodeproj/xcshareddata/xcschemes/Elysis.xcscheme
  Elysis/Controller/TelaDaPagina/HistoryModel.swift
  Elysis/Controller/TelaDaPagina/PontaDaPaginaAnimada.swift
  Elysis/ElysisRelease.entitlements
  Elysis/Model/ApiController.swift
  Elysis/Model/TelaDaPagina/HistoryModel.swift
  ElysisTests/ApiControllerTests.swift
  ElysisTests/ElysisTests.swift
  ElysisTests/GameStationTests.swift
  ElysisTests/HistoryModelTests.swift
Labels: documentation, enhancement

#22 Integrar
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/Credits.swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
  Elysis/Controller/ViewController.swift
  Elysis/Model/HistoryModel.swift
  Elysis/View/Assets.xcassets/Cover.imageset/Cover.png
  Elysis/View/Assets.xcassets/ImagemCapaMuitaQualidade.imageset/Contents.json
  Elysis/View/Assets.xcassets/ImagemCapaMuitaQualidade.imageset/ImagemCapaMuitaQualidade.png
  Elysis/View/Assets.xcassets/LettersCover.imageset/LettersCover.png
  Elysis/View/Assets.xcassets/MinhaIdeiaCapa.imageset/MinhaIdeiaCapa.png
  Elysis/View/Assets.xcassets/SimboloFinal.imageset/Contents.json
  Elysis/View/Assets.xcassets/SimboloFinal.imageset/SimboloFinal.png
  Elysis/View/Assets.xcassets/TextoFadeInOut.imageset/Contents.json
  Elysis/View/Assets.xcassets/TextoFadeInOut.imageset/TextoFadeInOut.png
Labels: enhancement

#23 Integrar
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
Labels: bug, enhancement

#24 Dev
  Elysis.xcodeproj/project.pbxproj
  Elysis.xcodeproj/xcshareddata/xcschemes/Elysis.xcscheme
  Elysis/Controller/Credits.swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/TelaDaPagina/PontaDaPaginaAnimada.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
  Elysis/Controller/ViewController.swift
  Elysis/ElysisRelease.entitlements
  Elysis/Model/ApiController.swift
  Elysis/Model/HistoryModel.swift
  Elysis/Model/TelaDaPagina/HistoryModel.swift
  Elysis/View/Assets.xcassets/Cover.imageset/Cover.png
  Elysis/View/Assets.xcassets/ImagemCapaMuitaQualidade.imageset/Contents.json
  Elysis/View/Assets.xcassets/ImagemCapaMuitaQualidade.imageset/ImagemCapaMuitaQualidade.png
  Elysis/View/Assets.xcassets/LettersCover.imageset/LettersCover.png
  Elysis/View/Assets.xcassets/MinhaIdeiaCapa.imageset/MinhaIdeiaCapa.png
  Elysis/View/Assets.xcassets/SimboloFinal.imageset/Contents.json
  Elysis/View/Assets.xcassets/SimboloFinal.imageset/SimboloFinal.png
  Elysis/View/Assets.xcassets/TextoFadeInOut.imageset/Contents.json
  Elysis/View/Assets.xcassets/TextoFadeInOut.imageset/TextoFadeInOut.png
  ElysisTests/ApiControllerTests.swift
  ElysisTests/ElysisTests.swift
  ElysisTests/GameStationTests.swift
  ElysisTests/HistoryModelTests.swift
Labels: enhancement

#25 Load tela
  Elysis.xcodeproj/project.pbxproj
  Elysis/Controller/ConstraintsPageViewController .swift
  Elysis/Controller/Credits.swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/SettingsViewController.swift
  Elysis/Controller/TelaDaPagina/Lapis.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
  Elysis/Controller/ViewController.swift
  Elysis/Model/ApiController.swift
  Elysis/Model/HistoryModel.swift
  Elysis/Model/SoundTrack.swift
  Elysis/View/Assets.xcassets/Lapis0.imageset/Lapis0.png
  Elysis/View/Assets.xcassets/Lapis1.imageset/Contents.json
  Elysis/View/Assets.xcassets/Lapis1.imageset/Lapis1.png
  Elysis/View/Assets.xcassets/Lapis2.imageset/Lapis2.png
  Elysis/View/Assets.xcassets/Lapis3.imageset/Contents.json
  Elysis/View/Assets.xcassets/Lapis3.imageset/Lapis3.png
  Elysis/View/Assets.xcassets/LapisColorido.imageset/Contents.json
  Elysis/View/Assets.xcassets/LapisColorido.imageset/LapisColorido.png
  Elysis/View/Assets.xcassets/LapisTransparente.imageset/Contents.json
  Elysis/View/Assets.xcassets/LapisTransparente.imageset/LapisTransparente.png
  Elysis/View/Assets.xcassets/void.dataset/Contents.json
  Elysis/View/Assets.xcassets/void.dataset/Void Theme V1.mp3
Labels: enhancement

#26 Bugs
  Elysis/Controller/AppDelegate.swift
  Elysis/Controller/ConstraintsPageViewController .swift
  Elysis/Controller/Credits.swift
  Elysis/Controller/PageViewController.swift
  Elysis/Controller/TelaDaPagina/Lapis.swift
  Elysis/Controller/TelaDaPagina/Pagina.swift
  Elysis/Controller/TelaDaPagina/TextoNormal.swift
  Elysis/Controller/ViewController.swift
  Elysis/View/Assets.xcassets/BackgroundGame.imageset/BackgroundGame.png
  Elysis/View/Assets.xcassets/BackgroundGame.imageset/Contents.json
  Elysis/View/Assets.xcassets/ImagemCapaMuitaQualidade.imageset/ImagemCapaMuitaQualidade.png
  Elysis/View/Assets.xcassets/ImagemCapaQualidade.imageset/Contents.json
  Elysis/View/Assets.xcassets/ImagemCapaQualidade.imageset/ImagemCapaQualidade.png
Labels: bug

#27 Traducao historia
  Elysis.xcodeproj/project.pbxproj
  Elysis/Model/HistoryData/english/HistoriaInicial.json
  Elysis/Model/HistoryData/english/Parte1.json
  Elysis/Model/HistoryData/english/negative.json
  Elysis/Model/HistoryData/english/neutral.json
  Elysis/Model/HistoryData/english/positive.json
  Elysis/Model/HistoryData/portuguese/aaaa.json
  Elysis/Model/HistoryData/portuguese/aleatoriopqnaoimporta.json
  Elysis/Model/HistoryData/portuguese/bbbb.json
  Elysis/Model/HistoryData/portuguese/cccc.json
  Elysis/Model/HistoryData/portuguese/sadasd.json
Labels: enhancement
